import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Poppins } from 'next/font/google';
import Footer from "@/components/footer/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300','400','500','600','700'],
});


 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} style={{color:"rgb(0,29,97)"}}>
        <Navbar/>
        <div style={{marginTop:'70px'}}>

        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
